services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./:/var/www/test-assignment.live
      - ./_docker/nginx/conf.d.prod:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    container_name: nginx
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/test-assignment.live
    depends_on:
      - mysql
    container_name: app
volumes:
  mysql_data:
    name: mysql_data
